// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service-build_docker.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	protobuf "github.com/ropenttd/tsubasa/generics/api/protobuf"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A BuildRequest is a request to the Build endpoint.
// BuildRequests return StatusResponse.
type BuildRequest struct {
	Source               *BuildRequest_BuildRequestSourceData `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target               *BuildRequest_BuildRequestTargetData `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_100418d7cf1ae1e0, []int{0}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetSource() *BuildRequest_BuildRequestSourceData {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *BuildRequest) GetTarget() *BuildRequest_BuildRequestTargetData {
	if m != nil {
		return m.Target
	}
	return nil
}

type BuildRequest_BuildRequestSourceData struct {
	Repo                 string            `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	BuildArgs            map[string]string `protobuf:"bytes,2,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BuildRequest_BuildRequestSourceData) Reset()         { *m = BuildRequest_BuildRequestSourceData{} }
func (m *BuildRequest_BuildRequestSourceData) String() string { return proto.CompactTextString(m) }
func (*BuildRequest_BuildRequestSourceData) ProtoMessage()    {}
func (*BuildRequest_BuildRequestSourceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_100418d7cf1ae1e0, []int{0, 0}
}

func (m *BuildRequest_BuildRequestSourceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest_BuildRequestSourceData.Unmarshal(m, b)
}
func (m *BuildRequest_BuildRequestSourceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest_BuildRequestSourceData.Marshal(b, m, deterministic)
}
func (m *BuildRequest_BuildRequestSourceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest_BuildRequestSourceData.Merge(m, src)
}
func (m *BuildRequest_BuildRequestSourceData) XXX_Size() int {
	return xxx_messageInfo_BuildRequest_BuildRequestSourceData.Size(m)
}
func (m *BuildRequest_BuildRequestSourceData) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest_BuildRequestSourceData.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest_BuildRequestSourceData proto.InternalMessageInfo

func (m *BuildRequest_BuildRequestSourceData) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *BuildRequest_BuildRequestSourceData) GetBuildArgs() map[string]string {
	if m != nil {
		return m.BuildArgs
	}
	return nil
}

type BuildRequest_BuildRequestTargetData struct {
	RepoName             string   `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	ImageVersion         string   `protobuf:"bytes,2,opt,name=image_version,json=imageVersion,proto3" json:"image_version,omitempty"`
	Tag                  []string `protobuf:"bytes,3,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest_BuildRequestTargetData) Reset()         { *m = BuildRequest_BuildRequestTargetData{} }
func (m *BuildRequest_BuildRequestTargetData) String() string { return proto.CompactTextString(m) }
func (*BuildRequest_BuildRequestTargetData) ProtoMessage()    {}
func (*BuildRequest_BuildRequestTargetData) Descriptor() ([]byte, []int) {
	return fileDescriptor_100418d7cf1ae1e0, []int{0, 1}
}

func (m *BuildRequest_BuildRequestTargetData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest_BuildRequestTargetData.Unmarshal(m, b)
}
func (m *BuildRequest_BuildRequestTargetData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest_BuildRequestTargetData.Marshal(b, m, deterministic)
}
func (m *BuildRequest_BuildRequestTargetData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest_BuildRequestTargetData.Merge(m, src)
}
func (m *BuildRequest_BuildRequestTargetData) XXX_Size() int {
	return xxx_messageInfo_BuildRequest_BuildRequestTargetData.Size(m)
}
func (m *BuildRequest_BuildRequestTargetData) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest_BuildRequestTargetData.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest_BuildRequestTargetData proto.InternalMessageInfo

func (m *BuildRequest_BuildRequestTargetData) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *BuildRequest_BuildRequestTargetData) GetImageVersion() string {
	if m != nil {
		return m.ImageVersion
	}
	return ""
}

func (m *BuildRequest_BuildRequestTargetData) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func init() {
	proto.RegisterType((*BuildRequest)(nil), "v1.BuildRequest")
	proto.RegisterType((*BuildRequest_BuildRequestSourceData)(nil), "v1.BuildRequest.BuildRequestSourceData")
	proto.RegisterMapType((map[string]string)(nil), "v1.BuildRequest.BuildRequestSourceData.BuildArgsEntry")
	proto.RegisterType((*BuildRequest_BuildRequestTargetData)(nil), "v1.BuildRequest.BuildRequestTargetData")
}

func init() { proto.RegisterFile("service-build_docker.proto", fileDescriptor_100418d7cf1ae1e0) }

var fileDescriptor_100418d7cf1ae1e0 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x6a, 0x14, 0x41,
	0x10, 0xc6, 0x9d, 0x19, 0xb3, 0xb8, 0xbd, 0x51, 0x42, 0x23, 0xb2, 0x8c, 0x07, 0x97, 0x78, 0x30,
	0x20, 0x3b, 0x43, 0x56, 0x08, 0x41, 0x04, 0x31, 0x44, 0x04, 0x0f, 0x1e, 0x26, 0xea, 0x75, 0xa9,
	0x99, 0x2d, 0xdb, 0x66, 0x67, 0xba, 0xc7, 0xee, 0xea, 0x09, 0x01, 0x5f, 0xd0, 0x57, 0xf0, 0x22,
	0xf8, 0x24, 0xd2, 0xdd, 0x6e, 0xcc, 0x06, 0x0f, 0x7b, 0xab, 0x3f, 0x5f, 0x55, 0xff, 0xbe, 0xa6,
	0x58, 0x6e, 0xd1, 0x0c, 0xb2, 0xc1, 0x79, 0xed, 0x64, 0xbb, 0x5a, 0xae, 0x74, 0xb3, 0x46, 0x53,
	0xf4, 0x46, 0x93, 0xe6, 0xe9, 0x70, 0x9c, 0x9f, 0x08, 0x49, 0x5f, 0x5d, 0x5d, 0x34, 0xba, 0x2b,
	0xbb, 0x4b, 0x49, 0x6b, 0x7d, 0x59, 0x0a, 0x3d, 0x0f, 0x82, 0xf9, 0x00, 0xad, 0x5c, 0x01, 0x69,
	0x63, 0xcb, 0xeb, 0x30, 0xce, 0xe6, 0xef, 0x6f, 0xcc, 0x19, 0xdd, 0xa3, 0x22, 0x5a, 0x95, 0x64,
	0x5d, 0x0d, 0x16, 0x4a, 0x81, 0x0a, 0x8d, 0x6c, 0x6c, 0x09, 0xbd, 0x2c, 0x83, 0xbe, 0x76, 0x5f,
	0x36, 0xd5, 0xb9, 0x95, 0x42, 0x41, 0xdb, 0x4a, 0x25, 0xe2, 0xae, 0xc3, 0x9f, 0x19, 0xdb, 0x3f,
	0xf3, 0x78, 0x15, 0x7e, 0x73, 0x68, 0x89, 0xbf, 0x66, 0x23, 0xab, 0x9d, 0x69, 0x70, 0x9a, 0xcc,
	0x92, 0xa3, 0xc9, 0xe2, 0x59, 0x31, 0x1c, 0x17, 0x37, 0x15, 0x5b, 0xc9, 0x45, 0x90, 0x9e, 0x03,
	0x41, 0xf5, 0x77, 0xcc, 0x2f, 0x20, 0x30, 0x02, 0x69, 0x9a, 0xee, 0xb0, 0xe0, 0x63, 0x90, 0xc6,
	0x05, 0x71, 0x2c, 0xff, 0x91, 0xb0, 0x47, 0xff, 0x7f, 0x83, 0xe7, 0xec, 0xae, 0xc1, 0x5e, 0x07,
	0xb4, 0xf1, 0xd9, 0xe8, 0xf7, 0xaf, 0x27, 0xe9, 0x2c, 0xa9, 0x42, 0x8d, 0x7f, 0x62, 0x2c, 0xfe,
	0x33, 0x18, 0x61, 0xa7, 0xe9, 0x2c, 0x3b, 0x9a, 0x2c, 0x4e, 0x76, 0x84, 0x8f, 0xe5, 0x37, 0x46,
	0xd8, 0xb7, 0x8a, 0xcc, 0x55, 0x35, 0xae, 0x37, 0x79, 0xfe, 0x8a, 0x3d, 0xd8, 0x6e, 0xf2, 0x03,
	0x96, 0xad, 0xf1, 0x2a, 0x32, 0x54, 0x3e, 0xe4, 0x0f, 0xd9, 0xde, 0x00, 0xad, 0xc3, 0xe0, 0x78,
	0x5c, 0xc5, 0xe4, 0x65, 0x7a, 0x9a, 0xe4, 0xdf, 0xb7, 0xad, 0xfc, 0x73, 0xcb, 0x9f, 0xb2, 0xb1,
	0xc7, 0x5e, 0x2a, 0xe8, 0xf0, 0x96, 0x9f, 0x7b, 0xbe, 0xf1, 0x01, 0x3a, 0xe4, 0xcf, 0xd9, 0x7d,
	0xd9, 0x81, 0xc0, 0xe5, 0x80, 0xc6, 0x4a, 0xad, 0xe2, 0x03, 0xd7, 0xc2, 0xfd, 0xd0, 0xfc, 0x1c,
	0x7b, 0x9e, 0x8b, 0x40, 0x4c, 0xb3, 0x59, 0xe6, 0xb9, 0x08, 0xc4, 0xe2, 0x1d, 0x9b, 0x9c, 0x87,
	0xa3, 0x0b, 0x0c, 0xfc, 0x94, 0xed, 0xc5, 0xe0, 0xe0, 0xf6, 0xb7, 0xe4, 0x8f, 0x7d, 0x65, 0x73,
	0x3a, 0xc5, 0x05, 0x01, 0x39, 0x5b, 0xa1, 0xed, 0xb5, 0xb2, 0x78, 0x78, 0xa7, 0x1e, 0x85, 0x63,
	0x79, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x54, 0xa4, 0xb0, 0x29, 0xd2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DockerBuildClient is the client API for DockerBuild service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DockerBuildClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*protobuf.StatusResponse, error)
}

type dockerBuildClient struct {
	cc *grpc.ClientConn
}

func NewDockerBuildClient(cc *grpc.ClientConn) DockerBuildClient {
	return &dockerBuildClient{cc}
}

func (c *dockerBuildClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*protobuf.StatusResponse, error) {
	out := new(protobuf.StatusResponse)
	err := c.cc.Invoke(ctx, "/v1.DockerBuild/Build", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerBuildServer is the server API for DockerBuild service.
type DockerBuildServer interface {
	Build(context.Context, *BuildRequest) (*protobuf.StatusResponse, error)
}

// UnimplementedDockerBuildServer can be embedded to have forward compatible implementations.
type UnimplementedDockerBuildServer struct {
}

func (*UnimplementedDockerBuildServer) Build(ctx context.Context, req *BuildRequest) (*protobuf.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}

func RegisterDockerBuildServer(s *grpc.Server, srv DockerBuildServer) {
	s.RegisterService(&_DockerBuild_serviceDesc, srv)
}

func _DockerBuild_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerBuildServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DockerBuild/Build",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerBuildServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DockerBuild_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DockerBuild",
	HandlerType: (*DockerBuildServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _DockerBuild_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service-build_docker.proto",
}
