// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service-build_docker.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "github.com/ropenttd/tsubasa/generics/api/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *BuildRequest) Validate() error {
	if this.Source != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Source); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Source", err)
		}
	}
	if this.Target != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Target); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Target", err)
		}
	}
	return nil
}
func (this *BuildRequest_BuildRequestSourceData) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *BuildRequest_BuildRequestTargetData) Validate() error {
	return nil
}
